/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2095.0) */

#include "ble_environmental_sensing_service.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside ENVIRONMENTAL SENSING SERVICE packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside ENVIRONMENTAL SENSING SERVICE packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_TEMPERATURE_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Temperature. */ 

/**@brief Function for encoding Temperature.
 *
 * @param[in]   p_temperature              Temperature characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t temperature_encode(ble_environmental_sensing_service_temperature_t * p_temperature, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_int16_encode(&p_temperature->temperature, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_environmental_sensing_service       ENVIRONMENTAL SENSING SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_evt_t * p_ble_evt)
{
    p_environmental_sensing_service->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_environmental_sensing_service       ENVIRONMENTAL SENSING SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_environmental_sensing_service->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_environmental_sensing_service       ENVIRONMENTAL SENSING SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_environmental_sensing_service->temperature_handles.cccd_handle)
    {
        if(p_environmental_sensing_service->evt_handler != NULL)
        {
            ble_environmental_sensing_service_evt_t evt;
            evt.evt_type = BLE_ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_environmental_sensing_service->evt_handler(p_environmental_sensing_service, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_environmental_sensing_service       ENVIRONMENTAL SENSING SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_environmental_sensing_service_on_ble_evt(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_environmental_sensing_service, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_environmental_sensing_service, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_environmental_sensing_service, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_environmental_sensing_service, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the ENVIRONMENTAL SENSING SERVICE. */
uint32_t ble_environmental_sensing_service_init(ble_environmental_sensing_service_t * p_environmental_sensing_service, const ble_environmental_sensing_service_init_t * p_environmental_sensing_service_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_environmental_sensing_service->evt_handler = p_environmental_sensing_service_init->evt_handler;
    p_environmental_sensing_service->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    BLE_UUID_BLE_ASSIGN(ble_uuid, 0x181A);
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_environmental_sensing_service->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Temperature characteristic
    ble_environmental_sensing_service_temperature_t temperature_initial_value = p_environmental_sensing_service_init->ble_environmental_sensing_service_temperature_initial_value; 
    p_environmental_sensing_service->is_temperature_notify_supported = p_environmental_sensing_service_init->is_temperature_notify_supported;

    uint8_t temperature_encoded_value[MAX_TEMPERATURE_LEN];
    ble_add_char_params_t add_temperature_params;
    memset(&add_temperature_params, 0, sizeof(add_temperature_params));
    
    add_temperature_params.uuid                = 0x2A6E; 
    add_temperature_params.max_len             = MAX_TEMPERATURE_LEN;
    add_temperature_params.init_len            = temperature_encode(&temperature_initial_value, temperature_encoded_value);
    add_temperature_params.p_init_value        = temperature_encoded_value; 
    add_temperature_params.char_props.notify   = p_environmental_sensing_service->is_temperature_notify_supported; 
    add_temperature_params.char_props.read     = 1; 
    add_temperature_params.read_access         = SEC_OPEN; 
    add_temperature_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_temperature_params.is_var_len          = 1; 

    err_code = characteristic_add(p_environmental_sensing_service->service_handle, &add_temperature_params, &(p_environmental_sensing_service->temperature_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Temperature. */
uint32_t ble_environmental_sensing_service_temperature_set(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_environmental_sensing_service_temperature_t * p_temperature)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_TEMPERATURE_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = temperature_encode(p_temperature, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_environmental_sensing_service->conn_handle, p_environmental_sensing_service->temperature_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Temperature. */
uint32_t ble_environmental_sensing_service_temperature_send(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_environmental_sensing_service_temperature_t * p_temperature)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_environmental_sensing_service->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_TEMPERATURE_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = temperature_encode(p_temperature, encoded_value);
        hvx_params.handle = p_environmental_sensing_service->temperature_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_environmental_sensing_service->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

