/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2095.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_dis.h" 
#include "ble_bas.h" 
#include "ble_environmental_sensing_service.h" 

static ble_dis_t    m_dis; 
static ble_bas_t    m_bas; 
static ble_environmental_sensing_service_t    m_environmental_sensing_service; 

static ble_environmental_sensing_service_temperature_t m_temperature;

uint8_t	m_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value_data_arr[1]; 


/**@brief Function for handling the Device Information events.
 *
 * @details This function will be called for all Device Information events which are passed to
 *          the application.
 *
 * @param[in]   p_device_information   Device Information structure.
 * @param[in]   p_evt   Event received from the Device Information.
 */
static void on_dis_evt(ble_dis_t * p_dis, ble_dis_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for handling the Battery Service events.
 *
 * @details This function will be called for all Battery Service events which are passed to
 *          the application.
 *
 * @param[in]   p_battery_service   Battery Service structure.
 * @param[in]   p_evt   Event received from the Battery Service.
 */
static void on_bas_evt(ble_bas_t * p_bas, ble_bas_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for handling the ENVIRONMENTAL SENSING SERVICE events.
 *
 * @details This function will be called for all ENVIRONMENTAL SENSING SERVICE events which are passed to
 *          the application.
 *
 * @param[in]   p_environmental_sensing_service   ENVIRONMENTAL SENSING SERVICE structure.
 * @param[in]   p_evt   Event received from the ENVIRONMENTAL SENSING SERVICE.
 */
static void on_environmental_sensing_service_evt(ble_environmental_sensing_service_t * p_environmental_sensing_service, ble_environmental_sensing_service_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: ENVIRONMENTAL_SENSING_SERVICE_TEMPERATURE evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_dis_init_t    dis_init; 
    ble_bas_init_t    bas_init; 
    ble_environmental_sensing_service_init_t    environmental_sensing_service_init; 
    

    // Initialize Device Information.
    memset(&dis_init, 0, sizeof(dis_init));

    dis_init.evt_handler = on_dis_evt; 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_manufacturer_name_string_initial_value.manufacturer_name, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_model_number_string_initial_value.model_number, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_serial_number_string_initial_value.serial_number, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_hardware_revision_string_initial_value.hardware_revision, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_firmware_revision_string_initial_value.firmware_revision, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_software_revision_string_initial_value.software_revision, "INITIAL VALUE"); 
    memset(&dis_init.ble_dis_system_id_initial_value.manufacturer_identifier,
           0x00,
           sizeof(dis_init.ble_dis_system_id_initial_value.manufacturer_identifier));
    memset(&dis_init.ble_dis_system_id_initial_value.organizationally_unique_identifier,
           0x00,
           sizeof(dis_init.ble_dis_system_id_initial_value.organizationally_unique_identifier));
    dis_init.ble_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value.data.list_len = 1;
    dis_init.ble_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value.data.p_list = m_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value_data_arr; 
    dis_init.ble_dis_pnp_id_initial_value.vendor_id_source.vendor_id_source = VENDOR_ID_SOURCE_BLUETOOTH_SIG_ASSIGNED_COMPANY_IDENTIFIER_VALUE_FROM_THE_ASSIGNED_NUMBERS_DOCUMENT; 
    memset(&dis_init.ble_dis_pnp_id_initial_value.vendor_id,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.vendor_id));
    memset(&dis_init.ble_dis_pnp_id_initial_value.product_id,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.product_id));
    memset(&dis_init.ble_dis_pnp_id_initial_value.product_version,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.product_version));

    err_code = ble_dis_init(&m_dis, &dis_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize Battery Service.
    memset(&bas_init, 0, sizeof(bas_init));

    bas_init.evt_handler = on_bas_evt; 
    bas_init.is_battery_level_notify_supported = true;
    memset(&bas_init.ble_bas_battery_level_initial_value.level,
           0x00,
           sizeof(bas_init.ble_bas_battery_level_initial_value.level));

    err_code = ble_bas_init(&m_bas, &bas_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize ENVIRONMENTAL SENSING SERVICE.
    memset(&environmental_sensing_service_init, 0, sizeof(environmental_sensing_service_init));

    environmental_sensing_service_init.evt_handler = on_environmental_sensing_service_evt; 
    environmental_sensing_service_init.is_temperature_notify_supported = true;
    memset(&environmental_sensing_service_init.ble_environmental_sensing_service_temperature_initial_value.temperature,
           0x00,
           sizeof(environmental_sensing_service_init.ble_environmental_sensing_service_temperature_initial_value.temperature));

    err_code = ble_environmental_sensing_service_init(&m_environmental_sensing_service, &environmental_sensing_service_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_dis_on_ble_evt(&m_dis, p_ble_evt); 
    ble_bas_on_ble_evt(&m_bas, p_ble_evt); 
    ble_environmental_sensing_service_on_ble_evt(&m_environmental_sensing_service, p_ble_evt); 
}


uint32_t bluetooth_update_temperature(float temperature)
{
    uint32_t err_code;
    m_temperature.temperature = temperature * 100;
    err_code = ble_environmental_sensing_service_temperature_set(&m_environmental_sensing_service, &m_temperature);
    return err_code;
}
